package app.ui;

public enum MouseMode {
    DRAWING_ARC,
    DRAWING_CIRCLE,
    DRAWING_ELLIPSE,
    DRAWING_POLYGON,
    DRAWING_POLYLINE,
    DRAWING_RECTANGLE,
    DRAWING_SQUARE,
    SELECTION,
    PAN,
    UNION,
    INTERSECTION,
    XOR,
    SUBSTRACTION
    // ...
}
